service: my-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: ${opt:region}
  architecture: arm64

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          method: GET
          path: /hello

plugins:
  - serverless-esbuild
  - serverless-offline
